name: codefilling
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip=21.1.2
  - pytorch=2.7.1
  - torchvision
  - pip:
      - spconv-cu126
      - matplotlib==3.4.2
      - numpy
      - open3d
      - opencv-python
      - cython
      - pygame
      - tensorboardX
      - shapely
      - einops
      - pyyaml
      - icecream
      - pyquaternion
      - h5py
      - git+https://github.com/dimatura/pypcd.git
